### ISSUE TITLE
The implementation process and experimental results of using "soft targets".

### ISSUE THREAD

**Issue by zjwzcx** [xy-guo/LIGA-Stereo#11]
Hi Xiaoyang! Thanks for your great work.
In the Introduction of LIGA-Stereo, you mentioned

>  'Comparing with traditional knowledge distillation for recognition tasks, we did not take the final erroneous classification and regression predictions from the LiDAR model as “soft” targets, which we found benefits little for training stereo detection networks.'

Could you please elaborate on your implementation process and experimental results?

**Comment by xy-guo** [comment]
Instead of imitating features, the network takes the soft probability distribution predicted by LiDAR-network as targets for the classification branch. For the regression, we directly use L1-loss to fit the regression offsets predicted from the LiDAR networks.
