### ISSUE TITLE
pseudo-lidar coord

### ISSUE THREAD

**Issue by ksh11023** [xy-guo/LIGA-Stereo#14]
hello,

what's the difference between pseudo-lidar coodinate and Lidar coordinate?

Thankyou

**Comment by xy-guo** [comment]
Lidar coordinate system is aligned with raw LiDAR data. 

Pseudo-lidar coordinate system is aligned with the left camera. The transformation between the image coordinate and the pseudo-lidar coordinate is a pure rotation as follows:
[[0, 0, 1, 0],
[-1, 0, 0, 0],
[0, -1, 0, 0],
[0, 0, 0, 1]]

**Comment by ksh11023** [comment]
Thank you for the reply!

So, is Pseudo-Lidar coordinate in rectified camera coordinate? 

I have one more question regarding processing raw LIDAR point cloud for the teacher model.

<img width="399" alt="스크린샷 2022-06-17 오전 10 03 18" src="https://user-images.githubusercontent.com/50094436/174201992-023ad53a-f93b-494a-88b6-728fe9a4154f.png">

In stereo_kitti_dataset.py, 
After transforming  point cloud(in lidar coordinate ) -> point cloud(in rectified lidar coordinate ) why is this flip_this_image process needed? I think it's multiplying -1 to the X-axis(forward for Lidar coord).

Thank you.

**Comment by xy-guo** [comment]
It is for augmentation when training.

**Comment by ksh11023** [comment]
Thank you!
