### ISSUE TITLE
pseudo lidar coordinates

### ISSUE THREAD

**Issue by czy341181** [xy-guo/LIGA-Stereo#2]
Hi, thanks for your great work! 
I have a question about the coordinate system.

I notice that in the stereo_kitti_dataset.py file， there is the introduction of a pseudo-lidar coordinate system.

https://github.com/xy-guo/LIGA-Stereo/blob/aee3731a24a0ab1667e633e520cc89be2f135272/liga/datasets/kitti/stereo_kitti_dataset.py#L366

I would like to know why this function is not rect_to_lidar, but rect_to_lidar_pseudo?  Is there any difference in labelling between double and single purpose?

**Comment by czy341181** [comment]
https://github.com/xy-guo/LIGA-Stereo/blob/aee3731a24a0ab1667e633e520cc89be2f135272/liga/datasets/kitti/stereo_kitti_dataset.py#L367

pseudo_lidar=True， this function is not rect_to_lidar, but rect_to_lidar_pseudo?

**Comment by xy-guo** [comment]
By default, stereo-based 3D detection will construct data in camera view. The reason for using pseudo lidar coordinate is purely for compatibility and engineering tricks. Of course, you can convert all data into LiDAR-view. The only thing you need to do is to make sure the stereo features and the LiDAR features share the same coordinate system.

**Comment by czy341181** [comment]
got it, thanks for your timely reply
